### ISSUE TITLE
FirebaseAnalytics_SetConsent and FirebaseAnalytics_SetUserProperty don't work properly

### ISSUE THREAD

**Issue by Callsign54** [YoYoGames/GMEXT-Firebase#1]
Two of these GML Extension functions don't work properly.

[**FirebaseAnalytics_SetUserProperty (Javascript)**](https://github.com/YoYoGames/GMEXT-Firebase/blob/main/source/Firebase_gml/extensions/YYFirebaseAnalytics/FirebaseAnalytics.js#L36-L39)
The native function parameter should be a single struct.

[**FirebaseAnalytics_SetConsent (Java)**](https://github.com/YoYoGames/GMEXT-Firebase/blob/main/source/Firebase_gml/extensions/YYFirebaseAnalytics/AndroidSource/Java/YYFirebaseAnalytics.java#L63)
Causes the following error.
> 02-10 03:54:41.091 24283 24445 I yoyo    : InvocationTargetException thrown trying to call method FirebaseAnalytics_SetConsent on YYFirebaseAnalytics
02-10 03:54:41.093 24283 24445 I yoyo    : Target exception: null. Cause: null. Stack trace: 
02-10 03:54:41.093 24283 24445 I yoyo    : java.lang.UnsupportedOperationException

**Comment by DiasFranciscoA** [comment]
Thank you for letting us know we will look into these bugs

**Comment by jzavala-YYG** [comment]
SHA: c600d77725dde10e7e141c9df76c4cb526238598
