### ISSUE TITLE
[PENDING] [MISSING CREDENTIALS] Firebase database extension - File google-services.json is missing

### ISSUE THREAD

**Issue by BlueShadow10** [YoYoGames/GMEXT-Firebase#11]
Hi!
When I compile a project for android with the latest firebase database extension on marketplace I get the following error.
It says the file google-services.json is missing even though is present in the indicated folder.

I just created a project of an almost empty room with just a few objects and the Firebase Database Extension. I setted the google-services.json path in the properties of the extension but I get the error and I can't compile for android.

Any advice is really appreciated.
Thank you.

> File google-services.json is missing. The Google Services Plugin cannot function without it.
Searched Location:
C:\Users\Luca\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\BLANK_GAME_BE378674_D22F9E8E\android\Default\com.company.game\google-services.json

Ide: 2023.8.1.102
Runtime: 2023.8.1.148
Os: Windows 10
Platform: Android

[bugFirebase.zip](https://github.com/YoYoGames/GMEXT-Firebase/files/12782733/bugFirebase.zip)

**Comment by DiasFranciscoA** [comment]
@BlueShadow10 We will need some extra information for that we will need you to go into the extension config panel and change the Log level to 2 this will log everything. We will need this extra information to check what is actually failing

**Comment by BlueShadow10** [comment]
Hi!
I attached the game project with the level 2 log.
Let me know if you need something else.

Thank you for your help ;)
[bugFirebase_logLevel2.zip](https://github.com/YoYoGames/GMEXT-Firebase/files/12832533/bugFirebase_logLevel2.zip)

**Comment by DiasFranciscoA** [comment]
@BlueShadow10 we were not able to reproduce this so we might be having a problem with an out of sync (outdated) FirebaseSetup extension... please make sure you have a recent version of this extension. I would ask you if possible to clone this repo and copy the FirebaseSetup extension (Firebase_gml\extensions\FirebaseSetup) folder into your project (overwriting if needed) and try building again. It could be that the marketplace version is not up-to-date and if that is the case we will update it shortly (as soon as this test passes).

Thank you so much for reaching out to us with your issue.

**Comment by BlueShadow10** [comment]
I downloaded the repository as a zip file, I copied the file from the _Firebase_gml\extensions\FirebaseSetup_ folder into my almost empty project (Project_name\extensions\FirebaseSetup), cleaned the project and run. The error is the same.
The  google-services.json file is copied in the folder mentioned in the output when I run the game (date/hour up to date), but game maker tells me again the file is not found...

I uploaded to you the project and log so maybe you can see if I used the updated code...
Tell me if I need to do other tests.
Thank you ;)

[firebase bug.zip](https://github.com/YoYoGames/GMEXT-Firebase/files/12871453/firebase.bug.zip)

**Comment by DiasFranciscoA** [comment]
Okay after afurther analysis it seems that the required file is being copied into a:
```
..\FirebaseSetup\AndroidSource\ProjectFiles\google-services.json\google-services.json
```

instead of the usual:
```
..\FirebaseSetup\AndroidSource\ProjectFiles\google-services.json
```

Please make sure of 2 things the path you are selecting in the extension option is a FILEPATH and not a folder path:
for this please provide us a screenshot of the following folder:
```
C:\MieiDati\GameMaker\DatiApp\configFirebase\
```

and also make sure to go into your projects folder and delete the folder `ProjectFiles` inside the following folder:
```
...\GameMakerStudio2\BLANK GAME - pet test\extensions\FirebaseSetup\AndroidSource\
```

Also when you update the `FirebaseSetup` extension you need to also update all the `.bat` and `.sh` files inside there... those are the ones responsible for copying the files over so they are required to be update too.

**Comment by BlueShadow10** [comment]
OK I was able to read some data from the database ;)
The problem was the folder _ProjectFiles_. It was still present probably from previous installations of the extension... 

Thank you for your help ;)
