### ISSUE TITLE
[ISSUE] High ANR error after update apps on google play

### ISSUE THREAD

**Issue by Matacapos** [YoYoGames/GMEXT-Firebase#12]
Hello. It's been a year since I updated my apps and now when I did I found that I had a very large number of errors. I did nothing more than update the firebase/admob plugins and update to the sdk/jdk that says android configuration recommended by game maker (on the guide). The common error is this (in crashlytics): com.xxxx.DemoRenderer.onDrawFrame (DemoRenderer.java:507=com.xxxx.DemoRenderer.onDrawFrame (DemoRenderer.java:507)

I leave images of the error and in case of doubts of the extensions I use (always use the same ones, do not add any, just update the ones that were updateable)

![error](https://github.com/YoYoGames/GMEXT-Firebase/assets/147455020/f2fc389f-460d-46eb-ac91-6095b9ee2d98)
![error01](https://github.com/YoYoGames/GMEXT-Firebase/assets/147455020/bf1d403b-aa1b-4eaf-a7ce-f3d36353f35a)
![error02](https://github.com/YoYoGames/GMEXT-Firebase/assets/147455020/1e3872d5-02f1-4267-938a-38702b2ac38b)
![extensions](https://github.com/YoYoGames/GMEXT-Firebase/assets/147455020/d9e44579-e538-447d-97bb-70a072fb0fb5)

**Comment by DiasFranciscoA** [comment]
So you are using FirebaseCrashlytics and AdMob these were the only two that got updated, appart from the JDK|NDK, correct?
Thank you for letting us know we will investigate the problem and get back in touch with you if necessary.

**Comment by Matacapos** [comment]
> So you are using FirebaseCrashlytics and AdMob these were the only two that got updated, appart from the JDK|NDK, correct? Thank you for letting us know we will investigate the problem and get back in touch with you if necessary.

Exactly.

**Comment by jzavala-YYG** [comment]
Hi @Matacapos did you updated/modified something in your draw events? A crash onDrawFrame suggest an issue in some draw event

**Comment by Matacapos** [comment]
> Hi @Matacapos did you updated/modified something in your draw events? A crash onDrawFrame suggest an issue in some draw event
No. I literally updated what you posted above. Admob, Crashlytics, sdk, ndk. Nothing else.

**Comment by jzavala-YYG** [comment]
@Matacapos  Can you add logs of this kind in your code until found in where is crashing?

```
FirebaseCrashlytics_Log(object_get_name(object_index) + " event: " + string(event_type) + " - start")

more code...

FirebaseCrashlytics_Log(object_get_name(object_index) + " event: " + string(event_type) + " - 1")

more code....

FirebaseCrashlytics_Log(object_get_name(object_index) + " event: " + string(event_type) + " - 2")

more code...

FirebaseCrashlytics_Log(object_get_name(object_index) + " event: " + string(event_type) + " - end")
```

**Comment by jzavala-YYG** [comment]
Closed by inactivity
