### ISSUE TITLE
Firebase Analytics gives issues

### ISSUE THREAD

**Issue by chorrus** [YoYoGames/GMEXT-Firebase#13]
Hi,

I am using a Macbook with M1.

I am using Admob, Firebase Authentication, and Firebase RealTimeDatabase and it's working perfectly.

After adding Analytics, it stops working, when compiling to iOS, I get FirebaseCore.h file not found, GoogleMobileAds.h file not found, etc...

**Comment by DiasFranciscoA** [comment]
Thank you for reaching out we would need to check the output log from the IDE if you are able to provide it would make the debug process easier. If you prefer to keep the log private please file a bug from the IDE (new bug filing system) after running a failing project so all logs are included. Also make sure to through all the extensions (extension options, double click the asset) and select log level 2 so we can have more information! Thank you filing this way should create a ticket with all the necessary information and keep your data safe.

**Comment by DiasFranciscoA** [comment]
We are waiting for information on this, this issues was stale for too long.
If the problem persists please reopen the ticket.
