### ISSUE TITLE
Error with REST API

### ISSUE THREAD

**Issue by chorrus** [YoYoGames/GMEXT-Firebase#14]
Firebase Crashlytics Reporting To Server
---------------------------- GML ERROR REPORT START ----------------------------------

{ longMessage : "ERROR in
action number 1
of Mouse Event for Left Released
for object Obj_FirebaseAuthentication_SignIn_Anonymously:

DoAdd :1: undefined value
 at gml_Script_FirebaseAuthentication_SignIn_Anonymously (line 126) - 			FirebaseAuthentication_endpoint + "signUp?key=" + extension_get_option_value("YYFirebaseAuthentication","WebAPIKey"),
", script : "gml_Script_FirebaseAuthentication_SignIn_Anonymously", line : 126, stacktrace : [ "gml_Script_FirebaseAuthentication_SignIn_Anonymously (line 126)","gml_Object_Obj_FirebaseAuthentication_SignIn_Anonymously_Mouse_7 (line 5) - FirebaseAuthentication_SignIn_Anonymously()" ], message : "DoAdd :1: undefined value" }
-------------------------------- GML ERROR REPORT END -------------------------------

I took this crashlytics report from the base project but it does happen in my project too. It didn't happen before using the latest version.

**Comment by chorrus** [comment]
I assume it is REST API because it does work in HTML5, iOS and Android. That happens when testing on Mac.

**Comment by jzavala-YYG** [comment]
@chorrus This issue is fixed on BETA release
