### ISSUE TITLE
Calling FirebaseCrashlytics_Crash() inside exception_unhandled_handler() doesn't send data to Firebase

### ISSUE THREAD

**Issue by ampersandbear** [YoYoGames/GMEXT-Firebase#18]
IDE v2023.6.0.92 Runtime v2023.6.0.139

The title describes the issue we're having. Crashing the game with just a FirebaseCrashlytics_Crash() call works just fine.

Could it be because of the IDE - extension version mismatch?

**Comment by jzavala-YYG** [comment]
I replace  **_FirebaseCrashlytics_RecordException(errorStr);_** by **_FirebaseCrashlytics_Crash(errorStr);_** in the function **_exception_unhandled_handler_** using android and works as expected, I can see the crash on Firebase console.

Note: Don't forget unplug your device to report to Firebase console
