### ISSUE TITLE
[Remote Configs] : Add "realtime listeners" for the configs.

### ISSUE THREAD

**Issue by Callsign54** [YoYoGames/GMEXT-Firebase#22]
The current GMExt implementation does not have realtime configs listening functionality. It's quite easy to add with one listener method
`mFirebaseRemoteConfig.addOnConfigUpdateListener(new ConfigUpdateListener() {
    @Override
    public void onUpdate(ConfigUpdate configUpdate) {
        Log.d(TAG, "Updated keys: " + configUpdate.getUpdatedKeys());

        mFirebaseRemoteConfig.activate().addOnCompleteListener(new OnCompleteListener`

**Comment by jzavala-YYG** [comment]
Hi @Callsign54!

 **_mFirebaseRemoteConfig.activate(_** It's already implemented in FirebaseRemoteConfig_FetchAndActivate().

But you are right it's possible get realt-ime updates, for that **_FirebaseRemoteConfig_AddOnConfigUpdateListener()_** (Only work on Android and iOS) just got implemented.



@YYBartT 

void FirebaseRemoteConfig_AddOnConfigUpdateListener()
https://firebase.google.com/docs/reference/android/com/google/firebase/remoteconfig/ConfigUpdateListenerRegistration
Description:
Starts listening for real-time config updates from the Remote Config backend and automatically fetches updates from the RC backend when they are available.

NOTE: Function available only for Android & iOS.

async event:
"type": "FirebaseRemoteConfig_AddOnConfigUpdateListener"
"keys": array of strings
"success": boolean

**Comment by YYBartT** [comment]
Documented the new function `FirebaseRemoteConfig_AddOnConfigUpdateListener()` and updated the [wiki](https://github.com/YoYoGames/GMEXT-Firebase/wiki).
