### ISSUE TITLE
Game does not compile with Analytics Extension

### ISSUE THREAD

**Issue by Foxtrio** [YoYoGames/GMEXT-Firebase#24]
As far as I've checked, only the Analytics extension causes the issue.

```
`Execution failed for task ':com.foxtrio.physicsfun:mergeExtDexDebug'.
> Could not resolve all files for configuration ':com.foxtrio.physicsfun:debugRuntimeClasspath'.
   > Failed to transform play-services-measurement-api-21.5.0.aar (com.google.android.gms:play-services-measurement-api:21.5.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: C:\Users\marty\.gradle\caches\transforms-3\8b64f1735332dcb0ed5d1c47b91c9469\transformed\jetified-play-services-measurement-api-21.5.0-runtime.jar.
         > Error while dexing.`
```

**Comment by Foxtrio** [comment]
**Update**
Seems like the issue is related with Gradle version by looking at a [similar topic](https://github.com/firebase/flutterfire/issues/11853). I'm targeting API 34 (as soon you cannot push updates to Google Play without)

I rolled back to the previous GMExt Firebase version.

**Comment by jackerley** [comment]
Hi, I can compile a project that contains the Firebase Analytics extension with SDK 34 ok, I do get the warning about Gradle but it compiles and runs fine. 

In order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

**Comment by Foxtrio** [comment]
Hi @jackerley. Running this repository also gives me the same issue. (The same issue also now applies to Authentication SDK)

I have checked all the my SDKs and build tools etc. All seems to okay. One thing I noticed is that when getting a build, Game Maker automatically downloads the Android SDK Build Tool 30.0.3. Not sure if that makes it.

Do you think anything else as well?

**Comment by jackerley** [comment]
Can you give me the full compile log from a failed build? That'll give me something to go on.
Thanks,
Fritz
