### ISSUE TITLE
Firebase firestore ext querying information on HTML5 return a list instead of a struct

### ISSUE THREAD

**Issue by NotAnEmptyBox** [YoYoGames/GMEXT-Firebase#27]
(this is a question I asked in a closed issue)
Hello @jzavala-YYG,

Thank a lot for this useful and straight to the point response. It is a weird workaround and I hope it get fixed in future update but it get the job done. 

Sadly, I ran out in to another problem, when I query the collection and get the "value" in the async social event, window give me a struct with all the documents as I need it but html5 give me an array instead containing the documents. This give the same result when I get the value with "FirebaseFirestore_Collection_Listener" type. The problem with arrays is that they don't give us their id, so I have no way to get to a specific document to update it or delete it later. Here is the async event code that I changed to get the value even when it is in array format :
![Capture d’écran 2024-07-20 124134](https://github.com/user-attachments/assets/23472d0c-e2e2-48b0-aa9b-fa6e6bd2130b).
And here is the "value" firebase give me on html5 : 
![Capture d’écran 2024-07-20 123059](https://github.com/user-attachments/assets/94aec1fc-754b-4a01-a1db-092d30ec8719) and on window : 
![Capture d’écran 2024-07-20 123326](https://github.com/user-attachments/assets/3570a201-3417-4af9-ad79-9d7192664025).
I am still using the same version of gamemaker as when I wrote my other message. Should I create an other issue for this question or should I stay in this one?

Either way,  I hope you can help me with this or at least give me some answers to better understand how it work

Thank again!

_Originally posted by @NotAnEmptyBox in https://github.com/YoYoGames/GMEXT-Firebase/issues/25#issuecomment-2241234529_

**Comment by jzavala-YYG** [comment]
Hi @NotAnEmptyBox!

If I remember correctly same happen in all the other platforms (iOS, Android, REST API & Web).
I think it's possible create a new function to return the IDs as struct but it will take some time due add functions on REST API it's not so simple.

If you want attack this issue I recommend you attach the name of the document in the content of the same document, you can do it at the moment of create if you are defining the name or you can use **_Firebase Functions_** that are functions in the server side.

Regards

**Comment by NotAnEmptyBox** [comment]
@jzavala-YYG 
Thanks you for the information!
That seem pretty complex indeed, I might try it myself but when you say to define the name of the document when creating it, how do I actually do that? I have seen no extension function with this option

**Comment by jzavala-YYG** [comment]
@NotAnEmptyBox 
In this 2 next functions you are defining the name of the document as **_MyDocumentName_**, you only need attach in the struct that you are writing and generate random names that never match with other.

FirebaseFirestore("Collection/**_MyDocumentName_**").Set({points: irandom(999999), value:"Opera"})
FirebaseFirestore("Collection/**_MyDocumentName_**").Update({value: choose("Opera","YoYoGames","GameMaker","Firebase"), points: random(999999)})

If you choose create Firebase functions I can help you after you success your first deploy:
https://firebase.google.com/docs/functions/get-started?gen=2nd

I think send random names for your docs it's enough. let me know if you success it to close this ticket.

Regards
