### ISSUE TITLE
Big Picture image on Local Notifications

### ISSUE THREAD

**Issue by Foxtrio** [YoYoGames/GMEXT-Firebase#28]
The current Local Notifications extension lacks the feature of displaying Image on the notification. Ability to do so would be nice.

In addition to that, it would also be cool if we could generate the notification images on runtime - perhaps through surfaces or buffers. I guess we could convert a surface to base64 image and send it off for the notification. I'm not sure about this though.

**Comment by jzavala-YYG** [comment]
Function added: **LocalPushNotification_Create_Android(ID,seconds,title,message,data,img_path)** 

Add customable icons to the notification it's only possible on Android.

**Comment by YYBartT** [comment]
Documented the new function `LocalPushNotification_Create_Android()` on the new [Local Notifications](https://github.com/YoYoGames/GMEXT-Firebase/wiki/local_notifications) wiki page, along with the other functionality of the Local Notifications extension.

**Comment by YYBartT** [comment]
Renamed the function `LocalPushNotification_Create_Android()` to `LocalPushNotification_Create_Ext()` in the documentation.
