### ISSUE TITLE
HTML5 setup still not working

### ISSUE THREAD

**Issue by cpt-jebediah** [YoYoGames/GMEXT-Firebase#33]
HTML5 setup still doesn't work despite the last update.
Also the new documentation is rather unclear

> Paste the struct's contents in a text editor, replace all double quotes " with single quotes ' and copy the resulting text. Also make sure to add single quotes ' to the struct keys.

What is this supposed to mean ? Replacing the doubles quotes by single quotes AND also add single quotes ?
I guess this redundancy is a mistake, an illustration would be welcome to clarify this mess.

But **anyway**, here is what I wrote in the Firebase Config Struct extension option, whith just single quotes replacing the double quotes :

`{apiKey: 'xxxxxxxxxxxxxxxxxxxx', authDomain: 'xxxxxxxxx.firebaseapp.com', projectId: 'xxxxxxxxxx', storageBucket: 'xxxxxxxxxxxxxx', messagingSend'risimanecopluserId: 'xxxxxxxxxxxx', appId: 'xxxxxxxxxxxxxxxxxxxxx', measurementId: 'xxxxxxxxxx'}`

![Firebase Config Struct](https://github.com/user-attachments/assets/f2856223-9c58-41ff-a78d-167092584d04)

When trying the demo provided with the extension in HTML5 export, pressing any button would crash the game and return the following error message in debug mode :

`Unhandled Exception - Uncaught SyntaxError: "undefined" is not valid JSON in file http://xxxxxxxxxxxx/index.html at line 1`

So their is either something important missing in the setup documentation, or the extension is just not supporting HTML5 export at all.
I have no trouble making the demo work for windows export.

**Comment by cpt-jebediah** [comment]
Well, I found that in the demo provided with the extension, Query actually works with HTML5 export.
I can thus read the data from my database, so my setup was correct.
However, adding a document would crash the game and return the following error :

`Unhandled Exception - SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data in file http://xxxxxxxxxxxxx/html5game/uph_FirebaseFirestore.js at line 13`

**Comment by DiasFranciscoA** [comment]
A struct is an object composed of key-value pairs the keys are the names of the members of the struct and the values are the values assign to each member. ~~In the point 5 of the [Platform Setup](https://github.com/YoYoGames/GMEXT-Firebase/wiki/platform_setup) for Web setup you can notice it says "add single quotes to the struct keys too". So `apiKey` should in fact be `'apiKey'` and the same applies to other keys in the struct.~~ 

**[EDIT]** You configuration is correct you just need to replace " with ' (no need to add single quotes to the keys themselves although there seems to be a problem with the string you wrote in the comment)

> `{apiKey: 'xxxxxxxxxxxxxxxxxxxx', authDomain: 'xxxxxxxxx.firebaseapp.com', projectId: 'xxxxxxxxxx', storageBucket: 'xxxxxxxxxxxxxx', messagingSend'risimanecopluserId: 'xxxxxxxxxxxx', appId: 'xxxxxxxxxxxxxxxxxxxxx', measurementId: 'xxxxxxxxxx'}` 

Note that in the string above the `messagingSend'risimanecopluserId` is not correct. The proper full string should be:

`{apiKey: 'xxxxxxxxxxxxxxxxxxx',authDomain: 'xxxxxxxxxxxxxxxxxxx',databaseURL: 'xxxxxxxxxxxxxxxxxxx',projectId: 'xxxxxxxxxxxxxxxxxxx',storageBucket: 'xxxxxxxxxxxxxxxxxxx',messagingSenderId: 'xxxxxxxxxxxxxxxxxxx',appId: 'xxxxxxxxxxxxxxxxxxx',measurementId: 'xxxxxxxxxxxxxxxxxxx'}`

In regards to the manual it will be updated with a proper image explaining this. Thank you for reaching out.

**Comment by DiasFranciscoA** [comment]
@cpt-jebediah This issues will be temporary closed until we have more feedback, if there is more information please reopen it.
