### ISSUE TITLE
Add Firebase App Check

### ISSUE THREAD

**Issue by Foxtrio** [YoYoGames/GMEXT-Firebase#34]
Firebase App Check provides security layer to the Firebase tools and make sure that all requests are from legit sources.

I am looking for a solution to restrict all Firebase tools from unauthorised sources. (Firestore f.ex)

**Comment by jzavala-YYG** [comment]
@YYBartT 

Setup

iOS
https://firebase.google.com/docs/app-check/ios/app-attest-provider
-App Attest
 
Android
https://firebase.google.com/docs/app-check/android/play-integrity-provider
-Play Integrity

Debug Mode

This Firebase module was created in 2 extensions YYFirebaseAppCheck and YYFirebaseAppCheck_Debug. if you enable one extension you should disable the other,
by default YYFirebaseAppCheck_Debug it's enabled

-----------------------------------------------------------

//Requests a Firebase App Check token. This method should be used ONLY if you need to authorize requests to a non-Firebase backend. Requests to Firebase backends are authorized automatically if configured.
void FirebaseAppCheck_GetToket(double _force_refresh)
		token: string
		success: bool

-----------------------------------------------------------
	
//Requests a Firebase App Check token. This method should be used ONLY if you need to authorize requests to a non-Firebase backend.

Returns limited-use tokens that are intended for use with your non-Firebase backend endpoints that are protected with Replay Protection. This method does not affect the token generation behavior of the FirebaseAppCheck_GetToket method.
void FirebaseAppCheck_LimitedUseToken()
		token: string
		success: bool

**Comment by DiasFranciscoA** [comment]
This issue will be now closed @Foxtrio as implemented, please check the documentation to see how to use the App Check module.
Please note that this new module while tested might still show some edge case bugs, if you find any let as know.

**Comment by Foxtrio** [comment]
@DiasFranciscoA yes I had tested it - along with the debug tokens.

However, I cannot test with the repository. There was a bug, something related to Firebase build scripts. I reported this, hope that'll be fixed.

Edit: My bad. Just saw the updated release. Thanks for the effort!
Disregard my message please.
