### ISSUE TITLE
[PENDING] [MISSING CREDENTIALS] Extension not building on Mac

### ISSUE THREAD

**Issue by tomShoutTheSecond** [YoYoGames/GMEXT-Firebase#5]
Attempting to build a game maker project using Firebase.Cloud.Messaging extension for the Android build target, on an OSX machine fails with the following error:

` File google-services.json is missing. The Google Services Plugin cannot function without it. `

In the build cache folder I see that instead of copying google-services.json as a file, a directory has been created with the name google-services.json. My entire game project has been copied to this directory.

Initially it seemed that removing whitespace from my build folder had resolved the issue, but after deleting and re-adding the Firebase.Cloud.Messaging extension I am seeing the issue without any path whitespace.

**Comment by DiasFranciscoA** [comment]
can you post a picture of your the FirebaseSetup extension, extension options panel? (the paths there should be pointing to the actual files on disk)

**Comment by DiasFranciscoA** [comment]
@tomShoutTheSecond we would like to know if this is still an issue. Please let us know if the problem is now solved.
