### ISSUE TITLE
Cant compile with latest extension, file copy error

### ISSUE THREAD

**Issue by rafhelp** [YoYoGames/GMEXT-Firebase#51]
Cant compile android app using VM mode.

The older version doesnt have this error:

E:\My Files\GameMaker2Projects\myapp\extensions\FirebaseSetup\pre_build_step.bat 
[FIREBASESETUP] INIT: Script initialization succeeded (v1.2.2 :: 1).
[FIREBASESETUP] WARN: Path 'E:\My Files\GameMaker2Projects\myapp\extensions\FirebaseSetup\iOSProjectFiles\' does not exist. Skipping deletion.
"Copying Android Firebase credentials into your project."
The system cannot find the file specified.
The system cannot find the path specified.
The system cannot find the path specified.
[FIREBASESETUP] ERROR: Failed to copy 'E:\My Files\MOBILE STUFF\myapp\google-services-fcm-uk-2024.json' to 'E:\My Files\GameMaker2Projects\myapp\extensions\FirebaseSetup\AndroidSource\ProjectFiles'.

**Comment by DiasFranciscoA** [comment]
Hello @rafhelp,

What version of the extension are you using?! Was this downloaded from the releases|marketplace or cloned from the actual repo?
Thank you so much for information provided.

**Comment by rafhelp** [comment]
> Hello [@rafhelp](https://github.com/rafhelp),
> 
> What version of the extension are you using?! Was this downloaded from the releases|marketplace or cloned from the actual repo? Thank you so much for information provided.

Both, I tried the one from GMS marketplace and also the one you have on your github (latest version)

**Comment by DiasFranciscoA** [comment]
Thank you for the response we wanted to know if you were using a clone from the repo... because that one should be working we are planning to update the release as soon as the Nov24 release happens since there are changes that need to be in for it to work correctly.
the problem you as experiencing is due to the fact that the path you're using as spaces in it.... `E:\My Files\MOBILE STUFF\myapp\google-services-fcm-uk-2024.json` also are you renaming the file to `google-services-fmc-uk-2024.json`? Note that using custom names might not be supported by the SDKs correctly.

**Comment by rafhelp** [comment]
OK il try that workaround.  but lots of local pc paths these days have spaces in them, as windows allows it, the path needs to be encapsulated say with '' or similar way. anyway thanks!

Regards,

 

    On Monday, 25 November 2024 at 13:10:53 GMT, DiasFranciscoA ***@***.***> wrote:  
 
 


Thank you for the response we wanted to know if you were using a clone from the repo... because that one should be working we are planning to update the release as soon as the Nov24 release happens since there are changes that need to be in for it to work correctly.
the problem you as experiencing is due to the fact that the path you're using as spaces in it.... E:\My Files\MOBILE STUFF\myapp\google-services-fcm-uk-2024.json also you are renaming the file to google-services-fmc-uk-2024.json note that those custom names might not work correctly.

**Comment by DiasFranciscoA** [comment]
This will be closed as it is fixed for next release (pending GameMaker 2024.11 release)
