### ISSUE TITLE
Add the possibility to send notification from GML with FCM

### ISSUE THREAD

**Issue by DeividHiGamboa** [YoYoGames/GMEXT-Firebase#54]
The FCM extension is missing a very important feature and that is the ability to send notification from GML, as it is used for many things such as creating chat systems and to be able to send a notification like WhatsApp does, or for many other things like something that happens within the game and thus the player can be notified, I would like you to take this into account and thank you in advance

**Comment by jzavala-YYG** [comment]
Hello @DeividHiGamboa 

Unfortunately there is no function that does this directly even using the native Firebase SDKs.

Let me enumerate the steps you will have to do achieve it.
1) Get the FCM token from the Android/iOS devices. (And refresh each time you open the app)
2) Store the FCM token in any database doing reference to firebase user identifier, we are already using Firebase so RealTime or Firestore it's preferable
3) Create a cloud function that catches the firebase user identifier, message and data that you want to send, get the token from your database using the firebase user identifier and finally send the nofication. https://firebase.google.com/docs/cloud-messaging/send-message
4) Handle the notification in the device.

Regards

**Comment by DeividHiGamboa** [comment]
Oh I understand, thank you very much for your reply!
