### ISSUE TITLE
Missing documentation for Cloud Storage and Cloud Functions

### ISSUE THREAD

**Issue by RhyminGarfunkle** [YoYoGames/GMEXT-Firebase#55]
The documentation pages for Cloud Storage and Cloud Functions are missing information on the functions for those extensions.

**Comment by YYBartT** [comment]
The wiki has been updated and should have all info on the missing functions on the [Cloud Storage](https://github.com/YoYoGames/GMEXT-Firebase/wiki/cloud_storage) page now.
