### ISSUE TITLE
[ISSUE] Erroring on Android on no internet connection

### ISSUE THREAD

**Issue by asda488** [YoYoGames/GMEXT-Firebase#6]
Hi, I raised this issue with help, and was redirected here, here is the edited message as sent to the helpdesk:
> Hello, while debugging a game with this on Huawei (and possibly Android), I have found what appears to be a bug (I could reproduce consistently): 
> Calling of the `FirebaseREST_HTTP_Failed_Authentication()` function from within the `Other_62 `script of `Obj_FirebaseREST_Listener_Once_Authentication` on Android will result in an error being thrown due to a ds_exists check on line 16 not behaving properly, `map_error["default"]` now contains the error message rather than `map_error["error"]` (mostly likely due to upstream change), hence the `ds_exist` will fail as it ends up with a string where it should take a DS type constant. 
> I have resolved this simply having "`errormessage = map_error["default"]` ". Similar code exists in `gml_GlobalScript_FirebaseREST_HTTP_Failed_Firestore` so I also changed it, however I am unsure whether this will have an effect. 

Additionally, I can provide screenshots of the evidence (as attached)

![v0euj7dx5mkb1](https://github.com/YoYoGames/GMEXT-Firebase/assets/39116917/e5196355-4f66-440f-aed8-b4405a1d2e41)
![ev7p8emw5mkb1](https://github.com/YoYoGames/GMEXT-Firebase/assets/39116917/9e271467-808d-423f-9864-827c03290a1a)

and a [link to a file](https://drive.google.com/file/d/1WivRznGpQu1e9iPt1-FwnLh7DuiyZTTc/view?usp=drive_link) that shows the error - install the apk file and run the program on an Android machine without Internet connection to reproduce the bug - the bug is specific to that platform only.

Unfortunately I am modding the project (porting from Windows to Android) and so it is not my own, I cannot supply a project file.
Please find an attempt at fixing it with pull request #7.

**Comment by jzavala-YYG** [comment]
SHA1: ac9d18af44885046fc10414a3d28c0f748ed84ed
