### ISSUE TITLE
[FEATURE] Open Source Improvement: Firebase Firestore data structures

### ISSUE THREAD

**Issue by terrydubois** [YoYoGames/GMEXT-Firebase#8]
### Is your feature request related to a problem?

While using the open-source [GameMaker Firebase Firestore library](https://marketplace.gamemaker.io/assets/10446/firebase-firestore-ext), you can only add numbers and strings to Firestore documents. In addition to numbers and strings, Firestore also supports arrays, maps, and any amount of nesting of the two. Being able to read and write these data structures would make the Firestore library more useful to engineers dealing with documents containing more complex data.

### Describe the solution you'd like

I have developed my own solution for this, expanding upon the original library. It is available on Github [here](https://github.com/rezonators/FirebaseDS). Using this expanded library, you can now use GameMaker's native structs and arrays to read and write this kind of data. While I have only engineered it to work with the REST API implementation, this can still be ported to all platforms. I believe this code could simply be merged with the original library to solve the issue.

### Describe alternatives you've considered

As an alternative, engineers can try to avoid using arrays and maps/structs in their Firestore documents. Another alternative is to use json_stringify and include array/struct data as a string on the document.

### Additional context

Working with my expanded Firestore library is no different than working with the original library. To include structs and arrays, just add them to the JSON being sent to Firestore as you would in GML normally. Additionally, I have added the "array_contains" query, which allows the querying of a collection to find documents that have an array containing a specific value.

**Comment by jzavala-YYG** [comment]
7f81b4b523b0fe81a1046187a17930fc94260cab
